[package]
name = "tiri"
version = "0.1.0"
edition = "2024"

[dependencies]
alacritty_terminal = "0.26"
anyhow = "1.0.104"
base64 = "0.23.1"
clap = { version = "4.6.7", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["serde"] }
font8x8 = "0.3.1"
libc = "0.2.190"
miniz_oxide = "0.9.1"
polling = "3"
portable-pty = "0.9.0"
postcard = { version = "1.1.3", features = ["use-std"] }
rustix = { version = "1", features = ["event", "fs", "process", "termios"] }
serde = { version = "1.0.229", features = ["derive"] }
tachyonfx = { version = "0.25.2", default-features = false, features = ["std", "std-duration"] }
ratatui-core = "0.1.2"
log = "0.4.34"
env_logger = { version = "0.11.11", default-features = false, features = ["humantime"] }
knus = "3.4.0"
miette = { version = "7.6.0", default-features = false, features = ["fancy-no-syscall"] }
unicode-width = "0.2"
compact_str = "0.9"
signal-hook = "0.4.5"
